
import { TranslationSet, Language } from './types';

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  [Language.EN]: {
    welcome: "Welcome,",
    savings: "Savings",
    loans: "Loans",
    transfer: "Transfer",
    agriLoan: "Agri-Loan",
    tradeLoan: "Trade-Loan",
    groupSavings: "Amana Asusu",
    bvnPrompt: "Enter BVN or NIN to Begin",
    verify: "Verify Identity",
    trustTagline: "Building Trust, Creating Wealth",
    creditScore: "Credit Health",
    checkEligibility: "Check Eligibility",
    totalBalance: "Total Balance",
    addMoney: "Add Money",
    quickActions: "Quick Actions",
    businessLoan: "Business Loan",
    billPayments: "Bill Payments",
    agriSupport: "Agri Support",
    recentTransactions: "Recent Transactions",
    seeAll: "See All",
    hikimarAmana: "Hikimar Amana",
    strategyInsight: "Strategy Insight",
    getAdvice: "Get Financial Tips",
    asusuTitle: "Amana Asusu",
    communitySavings: "Community Micro-Savings",
    activeRotations: "Your Rotations",
    joinGroup: "Join Group",
    contributeNow: "Contribute Now",
    profileTitle: "My Profile",
    logout: "Logout from Amana",
    trustIndex: "Trust Index",
    katsinaRank: "Katsina Rank",
    onboardingTitle: "Financial Inclusion For Katsina",
    onboardingSub: "Secure micro-banking with the Amana promise of trust.",
    secureLogin: "Secure Login"
  },
  [Language.HA]: {
    welcome: "Barka da zuwa,",
    savings: "Adana Kudi",
    loans: "Rance",
    transfer: "Tura Kudi",
    agriLoan: "Rancen Noma",
    tradeLoan: "Rancen Kasuwanci",
    groupSavings: "Asusun Amana",
    bvnPrompt: "Shigar da BVN ko NIN don farawa",
    verify: "Tabbatar da Kai",
    trustTagline: "Gina Dogaro, Samar da Arziki",
    creditScore: "Darajar Bashi",
    checkEligibility: "Duba Cancanta",
    totalBalance: "Jimillar Kudi",
    addMoney: "Kara Kudi",
    quickActions: "Ayyukan Gaggawa",
    businessLoan: "Rancen Kasuwanci",
    billPayments: "Biyan Kudade",
    agriSupport: "Tallafin Noma",
    recentTransactions: "Ma'amaloli na Kusa",
    seeAll: "Duba Duka",
    hikimarAmana: "Hikimar Amana",
    strategyInsight: "Hasken Hikima",
    getAdvice: "Shawarin Kudi",
    asusuTitle: "Asusun Amana",
    communitySavings: "Tashin Kudi na Al'umma",
    activeRotations: "Tashin Kudinka",
    joinGroup: "Shiga Rukunin",
    contributeNow: "Biya Yanzu",
    profileTitle: "Shafina",
    logout: "Fita daga Amana",
    trustIndex: "Matakin Dogaro",
    katsinaRank: "Matsayi a Katsina",
    onboardingTitle: "Tallafin Kudi Ga Katsina",
    onboardingSub: "Banki mai aminci tare da alkawarin amana.",
    secureLogin: "Shiga Ciki"
  }
};

export const THEME = {
  primary: '#065f46',
  secondary: '#b45309',
  accent: '#fef3c7',
  text: '#111827',
};
